In [3]:
import pymongo
import pandas as pd
from pymongo import MongoClient
client = MongoClient( 'localhost:27017' )
db = client['rios']
rios = db.rios
rios = pd.DataFrame(list(rios.find()))
rios_orden = rios[['nombre','longitud','cuenca_hidrografica','caudal','provincias']]
display(rios_orden)

,nombre,longitud,cuenca_hidrografica,caudal,provincias
0,Ebro,930.0,Ebro,426m³/s,"[Cantabria, Palencia, Burgos, La Rioja, Alava,..."
1,Duero,897.0,Duero,714m³/s,"[Soria, Burgos, Valladolid, Zamora, Salamanca,..."
2,Miño,350.0,Miño,340m³/s,"[Lugo, Ourense, Pontevedra, Viana do Castelo]"
3,Tajo,1038.0,Tajo,500m³/s,"[Teruel, Guadalajara, Cuenca, Madrid, Toledo, ..."
4,Jucar,509.0,Jucar,49m³/s,"[Cuenca, Albacete, Valencia]"
5,Guadiana,742.0,Guadiana,600m³/s,"[Albacete, Ciudad Real, Badajoz, Huelva, Porta..."
6,Segura,325.0,Segura,26m³/s,"[Jaen, Albacete, Murcia, Alicante]"
7,Guadalquivir,657.0,Guadalquivir,164m³/s,"[Jaen, Cordoba, Sevilla, Huelva, Cadiz]"